### ISSUE TITLE
Clairify create/update FTS in REST API

### ISSUE THREAD

**Issue by mgroves** [couchbase/docs-server#205]
I think the documentation for this page: https://docs.couchbase.com/server/6.0/rest-api/rest-fts-indexing.html (REST API reference -> REST API endpoint list -> Full Text Search API -> Indexes) can be changed to add more clarity around using the REST endpoint to update an existing FTS index.

See this SO discussion for a little more detail: https://stackoverflow.com/questions/53649340/couchbase-fts-index-update-through-rest-api/53659137

It's not entirely clear that you need to specify the existing uuid when trying to PUT an FTS index update. I'm not sure how best to make that clear, but basically if you try to execute a PUT to update an existing query, it will fail with an error message

> cannot create index because an index with the same name already exists

Also kinda related: if you try to execute a PUT to update an existing query and you use the wrong/outdated UUID, there will be an error message

> ...perhaps there was concurrent index definition update, current index UUID

**Comment by jamiltz** [comment]
Doc tickets are being tracked in JIRA. Can also be filed via the "Feedback?" button.

**Comment by jamiltz** [comment]
https://issues.couchbase.com/browse/DOC-4650
