### ISSUE TITLE
Outdated URL in Ubuntu install instructions?

### ISSUE THREAD

**Issue by mgroves** [couchbase/docs-server#267]
Referring to the docs here:

https://docs.couchbase.com/server/6.0/install/ubuntu-debian-install.html

The very first step says `curl -O http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-4-amd64.deb`. That can't be correct, can it? Surely this should point to a 6.0 release? Like https://packages.couchbase.com/releases/6.0.0/couchbase-server-enterprise_6.0.0-ubuntu16.04_amd64.deb and https://packages.couchbase.com/releases/6.0.0/couchbase-server-community_6.0.0-ubuntu16.04_amd64.deb ?

**Comment by jamiltz** [comment]
Doc tickets are being tracked in JIRA. Can also be filed via the "Feedback?" button.

**Comment by jamiltz** [comment]
https://issues.couchbase.com/browse/DOC-4651
